Repository warrenbuckley/Compact-Log-Format-Viewer, pull requests merged in 2022-12, with the labels that each got.

#703 Fixes casing problem for LogLevel - Updates to 2.0.0 of Serilog.Formatting.Compact.Reader
  LogViewer.Server/LogViewer.Server.csproj
Labels: bug

#726 Upgrades to .NET7
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/intellicode.yml
  .github/workflows/richcodenav.yml
  LogViewer.Server.Tests/LogViewer.Server.Tests.csproj
  LogViewer.Server/LogViewer.Server.csproj
Labels: dependencies, .NET

#673 Add CmdOrCtrl+Shift+W shortcut to close log file
  LogViewer.Client/src/main/appmenu.ts
Labels: enhancement

#727 Feature: signalR and FileSystemWatcher to notify of new changes to log file
  LogViewer.Client/package-lock.json
  LogViewer.Client/package.json
  LogViewer.Client/src/main/events.ts
  LogViewer.Client/src/renderer/app-angular.ts
  LogViewer.Client/styles/app.css
  LogViewer.Client/views/index.html
  LogViewer.Server.Tests/LogViewer.Server.Tests.csproj
  LogViewer.Server.Tests/ServerTests.cs
  LogViewer.Server/Hubs/LogHub.cs
  LogViewer.Server/Parser/LogParser.cs
  LogViewer.Server/Startup.cs
Labels: enhancement, minor

#728 Update versions in GitHub Workflow YML files
  .github/dependabot.yml
  .github/workflows/Release-Drafter.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/intellicode.yml
  .github/workflows/richcodenav.yml
Labels: dependencies
